package softexcel.fedmedco

class DataMap {

    static Map countryCodeMapping = ["BD": "BGD", "BE": "BEL", "BF": "BFA", "BG": "BGR", "BA": "BIH", "BB": "BRB",
                                     "WF": "WLF", "BL": "BLM", "BM": "BMU", "BN": "BRN", "BO": "BOL", "BH": "BHR",
                                     "BI": "BDI", "BJ": "BEN", "BT": "BTN", "JM": "JAM", "BV": "BVT", "BW": "BWA",
                                     "WS": "WSM", "BQ": "BES", "BR": "BRA", "BS": "BHS", "JE": "JEY", "BY": "BLR",
                                     "BZ": "BLZ", "RU": "RUS", "RW": "RWA", "RS": "SRB", "TL": "TLS", "RE": "REU",
                                     "TM": "TKM", "TJ": "TJK", "RO": "ROU", "TK": "TKL", "GW": "GNB", "GU": "GUM",
                                     "GT": "GTM", "GS": "SGS", "GR": "GRC", "GQ": "GNQ", "GP": "GLP", "JP": "JPN",
                                     "GY": "GUY", "GG": "GGY", "GF": "GUF", "GE": "GEO", "GD": "GRD", "GB": "GBR",
                                     "GA": "GAB", "SV": "SLV", "GN": "GIN", "GM": "GMB", "GL": "GRL", "GI": "GIB",
                                     "GH": "GHA", "OM": "OMN", "TN": "TUN", "JO": "JOR", "HR": "HRV", "HT": "HTI",
                                     "HU": "HUN", "HK": "HKG", "HN": "HND", "HM": "HMD", "VE": "VEN", "PR": "PRI",
                                     "PS": "PSE", "PW": "PLW", "PT": "PRT", "SJ": "SJM", "PY": "PRY", "IQ": "IRQ",
                                     "PA": "PAN", "PF": "PYF", "PG": "PNG", "PE": "PER", "PK": "PAK", "PH": "PHL",
                                     "PN": "PCN", "PL": "POL", "PM": "SPM", "ZM": "ZMB", "EH": "ESH", "EE": "EST",
                                     "EG": "EGY", "ZA": "ZAF", "EC": "ECU", "IT": "ITA", "VN": "VNM", "SB": "SLB",
                                     "ET": "ETH", "SO": "SOM", "ZW": "ZWE", "SA": "SAU", "ES": "ESP", "ER": "ERI",
                                     "ME": "MNE", "MD": "MDA", "MG": "MDG", "MF": "MAF", "MA": "MAR", "MC": "MCO",
                                     "UZ": "UZB", "MM": "MMR", "ML": "MLI", "MO": "MAC", "MN": "MNG", "MH": "MHL",
                                     "MK": "MKD", "MU": "MUS", "MT": "MLT", "MW": "MWI", "MV": "MDV", "MQ": "MTQ",
                                     "MP": "MNP", "MS": "MSR", "MR": "MRT", "IM": "IMN", "UG": "UGA", "TZ": "TZA",
                                     "MY": "MYS", "MX": "MEX", "IL": "ISR", "FR": "FRA", "IO": "IOT", "SH": "SHN",
                                     "FI": "FIN", "FJ": "FJI", "FK": "FLK", "FM": "FSM", "FO": "FRO", "NI": "NIC",
                                     "NL": "NLD", "NO": "NOR", "NA": "NAM", "VU": "VUT", "NC": "NCL", "NE": "NER",
                                     "NF": "NFK", "NG": "NGA", "NZ": "NZL", "NP": "NPL", "NR": "NRU", "NU": "NIU",
                                     "CK": "COK", "XK": "XKX", "CI": "CIV", "CH": "CHE", "CO": "COL", "CN": "CHN",
                                     "CM": "CMR", "CL": "CHL", "CC": "CCK", "CA": "CAN", "CG": "COG", "CF": "CAF",
                                     "CD": "COD", "CZ": "CZE", "CY": "CYP", "CX": "CXR", "CR": "CRI", "CW": "CUW",
                                     "CV": "CPV", "CU": "CUB", "SZ": "SWZ", "SY": "SYR", "SX": "SXM", "KG": "KGZ",
                                     "KE": "KEN", "SS": "SSD", "SR": "SUR", "KI": "KIR", "KH": "KHM", "KN": "KNA",
                                     "KM": "COM", "ST": "STP", "SK": "SVK", "KR": "KOR", "SI": "SVN", "KP": "PRK",
                                     "KW": "KWT", "SN": "SEN", "SM": "SMR", "SL": "SLE", "SC": "SYC", "KZ": "KAZ",
                                     "KY": "CYM", "SG": "SGP", "SE": "SWE", "SD": "SDN", "DO": "DOM", "DM": "DMA",
                                     "DJ": "DJI", "DK": "DNK", "VG": "VGB", "DE": "DEU", "YE": "YEM", "DZ": "DZA",
                                     "US": "USA", "UY": "URY", "YT": "MYT", "UM": "UMI", "LB": "LBN", "LC": "LCA",
                                     "LA": "LAO", "TV": "TUV", "TW": "TWN", "TT": "TTO", "TR": "TUR", "LK": "LKA",
                                     "LI": "LIE", "LV": "LVA", "TO": "TON", "LT": "LTU", "LU": "LUX", "LR": "LBR",
                                     "LS": "LSO", "TH": "THA", "TF": "ATF", "TG": "TGO", "TD": "TCD", "TC": "TCA",
                                     "LY": "LBY", "VA": "VAT", "VC": "VCT", "AE": "ARE", "AD": "AND", "AG": "ATG",
                                     "AF": "AFG", "AI": "AIA", "VI": "VIR", "IS": "ISL", "IR": "IRN", "AM": "ARM",
                                     "AL": "ALB", "AO": "AGO", "AQ": "ATA", "AS": "ASM", "AR": "ARG", "AU": "AUS",
                                     "AT": "AUT", "AW": "ABW", "IN": "IND", "AX": "ALA", "AZ": "AZE", "IE": "IRL",
                                     "ID": "IDN", "UA": "UKR", "QA": "QAT", "MZ": "MOZ"]

    static Map colorCodes = ["0":"ZERO", "10":"TEN",
                             "20": "TWENTY", "30": "THIRTY",
                             "40": "FORTY", "50":"FIFTY",
                             "60":"SIXTY", "70":"SEVENTY",
                             "80":"EIGHTY", "90":"NINETY",
                             "100": "HUNDRED"]

    static def hundredColorMap = null

    static def hundredColors = ["#CD4A4A",
                               "#CC6666",
                               "#BC5D58",
                               "#FF5349",
                               "#FD5E53",
                               "#FD7C6E",
                               "#FDBCB4",
                               "#FF6E4A",
                               "#FFA089",
                               "#EA7E5D",
                               "#B4674D",
                               "#A5694F",
                               "#FF7538",
                               "#FF7F49",
                               "#DD9475",
                               "#FF8243",
                               "#FFA474",
                               "#9F8170",
                               "#CD9575",
                               "#EFCDB8",
                               "#D68A59",
                               "#DEAA88",
                               "#FAA76C",
                               "#FFCFAB",
                               "#FFBD88",
                               "#FDD9B5",
                               "#FFA343",
                               "#EFDBC5",
                               "#FFB653",
                               "#E7C697",
                               "#8A795D",
                               "#FAE7B5",
                               "#FFCF48",
                               "#FCD975",
                               "#FDDB6D",
                               "#FCE883",
                               "#F0E891",
                               "#ECEABE",
                               "#BAB86C",
                               "#FDFC74",
                               "#FDFC74",
                               "#FFFF99",
                               "#C5E384",
                               "#B2EC5D",
                               "#87A96B",
                               "#A8E4A0",
                               "#1DF914",
                               "#76FF7A",
                               "#71BC78",
                               "#6DAE81",
                               "#9FE2BF",
                               "#1CAC78",
                               "#30BA8F",
                               "#3BB08F",
                               "#1CD3A2",
                               "#17806D",
                               "#158078",
                               "#1FCECB",
                               "#78DBE2",
                               "#77DDE7",
                               "#80DAEB",
                               "#414A4C",
                               "#199EBD",
                               "#1CA9C9",
                               "#1DACD6",
                               "#9ACEEB",
                               "#1A4876",
                               "#1974D2",
                               "#2B6CC4",
                               "#1F75FE",
                               "#C5D0E6",
                               "#B0B7C6",
                               "#5D76CB",
                               "#A2ADD0",
                               "#979AAA",
                               "#ADADD6",
                               "#7366BD",
                               "#7442C8",
                               "#7851A9",
                               "#9D81BA",
                               "#926EAE",
                               "#CDA4DE",
                               "#8F509D",
                               "#C364C5",
                               "#FB7EFD",
                               "#FC74FD",
                               "#8E4585",
                               "#FF1DCE",
                               "#FF1DCE",
                               "#FF48D0",
                               "#E6A8D7",
                               "#C0448F",
                               "#6E5160",
                               "#DD4492",
                               "#FF43A4",
                               "#F664AF",
                               "#FCB4D5",
                               "#FFBCD9",
                               "#F75394",
                               "#FFAACC",
                               "#E3256B",
                               "#FDD7E4",
                               "#CA3767"]



    static constraints = {
    }
}
